### ISSUE TITLE
File type detection

### ISSUE THREAD

**Issue by raprasad** [TwoRavens/raven-metadata-service#199]
Detect by extension and actual data.

e.g. csv delimited by tabs or semicolons

- [ ] construct table/list of extensions and possible types
- [ ] use detectors for actual content
- [ ] user error message should include acceptable formats

---

- may require use in the loop confirmation

**Comment by aaron-lebo** [comment]
Was about to file this and saw this...

https://github.com/TwoRavens/raven-metadata-service/blob/develop/test_data/RQOZIJ_food_range_sez_adj.csv

We're using this file as a sample in our docs. I noticed afterwards that it's getting tagged as having a single column because it is actually semicolon delimited.

https://github.com/TwoRavens/raven-metadata-service/blob/develop/test_data/RQOZIJ_food_range_sez_adj.json

Having done something similar at a prior dayjob, an option is to take x rows and run split y on them (x.split(',')). If all of those rows give you the same len() result, then you've likely get a file delimited by y. The ys you'd test would go from more common to less.
